version: '{build}'
image: Visual Studio 2017
branches:
    only:
      - master
environment:
  COVERALLS_REPO_TOKEN:
    secure: cbqlOmIX0yBIg1IsaBazw4VMFM8zL9Yaee77k2XsdsSN3cEXLkOHJ4knRlLxtzBE
before_build:
- cmd: before_build.cmd
build:
  project: CG.Pluralization.sln
  verbosity: minimal
test:
  categories:
    except:
    - Integration
after_test:
- cmd: after_test.cmd
artifacts:
- path: .\CG.Pluralization\bin\Debug\*.nupkg
  name: nuget-packages
deploy:
- provider: NuGet
  api_key:
    secure: LuRaS+cj/+AZmxpLROdHXR5vF4tvW42LzSmtphgkr3FLwQOl732UNtnmLiiAOXr1
  artifact: nuget-packages
